### ISSUE TITLE
Strange behaviour after update to 2.1.0.0

### ISSUE THREAD

**Issue by CMeyer-work** [AMSoftwareNL/crmpowershell#36]
Steps to reproduce
After updating to new version some calls returned strange results. This behaviour stops after reverting the update and using 2.0.0.0 again.

Expected behavior
For example the call of Get-CrmBusinessUnit with parameter -Name  returned the ID of a team with complete other name instead of the given BusinessUnit. Also Set-CrmUserTeams sets the team to another team instead of the one giving with the parameter -Teams

Actual behavior
After reverting the update everything is running well

Environment data
----------------

v2.1.0.0

**Comment by CMeyer-work** [comment]
Some additional info: 
In one of our scripts we are building up an array with all needed teams we have in CRM. For this we read from an excel file the team names and store the CRM GUID in an array. When we loop now through the teams the first call of Get-CrmTeam returns the ID for the first team correct. But every other team we read Get-CrmTeam returns the same ID from the first team. This ID is now returned from every call regardless which we use ( Get-Crmteam, Get-CrmBusinessunit,....)

**Comment by AMSoftwareNL** [comment]
The instance of the PropertyAdapter for entities/records creates a connection between the property and the record-instance using this adapter (apparently). So for all member properties of Entity after the first use, all other records return the same result as the first record :-| 
Workaround is to use the actual attribute for the Id (i.e. teamid) instead of the ID property. 

Will fix this over the weekend.

**Comment by AMSoftwareNL** [comment]
Fixed in v2.1.1.0 ... available in PSGallery
Pulled v2.1.0.0 so no longer available
